name = "privmsg"
main = "src/worker.js"
compatibility_date = "2026-04-17"

[observability]
enabled = true

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "privmsg"
database_id = "replace-with-d1-id"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "privmsg-payloads"
preview_bucket_name = "privmsg-payloads-preview"

[env.production]

[[env.production.d1_databases]]
binding = "DB"
database_name = "privmsg-prod"
database_id = "efb894c9-ebe4-4083-abea-655ed37f22ba"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "privmsg-payloads-prod"
preview_bucket_name = "privmsg-payloads-preview"

[env.staging]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "privmsg-staging"
database_id = "c7419cce-2f7d-4fd4-9471-041d5e6f6555"

[[env.staging.r2_buckets]]
binding = "BUCKET"
bucket_name = "privmsg"
preview_bucket_name = "privmsg-staging-payloads-preview"
